#!/bin/bash
set -e

TASK_ID=$1
TASK_DESCRIPTION=$2
CHANGES=$3
DECISIONS=$4
ALTERNATIVES=$5
TESTS=$6
LIMITATIONS=$7
REVIEW_GUIDANCE=$8

if [ -z "$TASK_ID" ] || [ -z "$TASK_DESCRIPTION" ]; then
    echo "Usage: generate-agent-pr-template.sh <task_id> <task_description> [changes] [decisions] [alternatives] [tests] [limitations] [review_guidance]"
    exit 1
fi

PR_TEMPLATE="## Task Description
${TASK_DESCRIPTION} (ID: ${TASK_ID})

## What Changed
${CHANGES:-_To be filled_}

## Key Design Decisions
${DECISIONS:-_To be filled_}

## Alternatives Considered
${ALTERNATIVES:-_To be filled_}

## Test Coverage
${TESTS:-_To be filled_}

## Known Limitations / Follow-up Tasks
${LIMITATIONS:-_To be filled_}

## Review Guidance
${REVIEW_GUIDANCE:-_To be filled_}

---
*This PR was generated by AI agent following Agent-Aware Git best practices*"

echo "$PR_TEMPLATE"

mkdir -p .github/pull_request_template
echo "$PR_TEMPLATE" > .github/pull_request_template/agent.md
echo ""
echo "PR template saved to .github/pull_request_template/agent.md"
